# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sendToken.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sendToken.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsendToken.proto\x12\x16tokenManager.sendToken\"\x1a\n\tSendToken\x12\r\n\x05token\x18\x01 \x01(\t\"B\n\x13VerifyTokenResponse\x12\x11\n\x04user\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x07success\x18\x02 \x01(\x08\x42\x07\n\x05_user2s\n\x12VerifyTokenService\x12]\n\x0bverifyToken\x12!.tokenManager.sendToken.SendToken\x1a+.tokenManager.sendToken.VerifyTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sendToken_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDTOKEN']._serialized_start=43
  _globals['_SENDTOKEN']._serialized_end=69
  _globals['_VERIFYTOKENRESPONSE']._serialized_start=71
  _globals['_VERIFYTOKENRESPONSE']._serialized_end=137
  _globals['_VERIFYTOKENSERVICE']._serialized_start=139
  _globals['_VERIFYTOKENSERVICE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
